
name: nodejs_init
version: 0.0.1
language: nodejs
description: "
  本插件主要是用作初始化本flow的NodeJs环境和输出环境变量（包括项目相关的变量和Node相关的变量），
例如 `FLOW_PROJECT_NAME`存的就是项目的名称，`FLOW_NODE_VERSION`存的Node版本等

- 注意事项
  此插件必须放在flow的第一个，否则会出现Node的环境问题"
public: true
tags:
  - nodejs
  - init
inputs:
outputs:
  - name: FLOW_NVM_VERSION
  - name: FLOW_NODE_VERSION
  - name: FLOW_NPM_VERSION
script_path: ./run.sh  
  
template: |  
  
  